--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: provider; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA provider;


ALTER SCHEMA provider OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: otp_logs; Type: TABLE; Schema: provider; Owner: postgres
--

CREATE TABLE provider.otp_logs (
    otp_log_id uuid NOT NULL,
    mobile_number character varying(32) NOT NULL,
    otp character varying(16) NOT NULL,
    expires_at timestamp with time zone,
    is_verified boolean,
    attempts integer,
    created_at timestamp with time zone,
    hashed_password character varying(255)
);


ALTER TABLE provider.otp_logs OWNER TO postgres;

--
-- Name: providers; Type: TABLE; Schema: provider; Owner: postgres
--

CREATE TABLE provider.providers (
    id bigint NOT NULL,
    mobile_number character varying NOT NULL,
    is_mobile_verified boolean DEFAULT false NOT NULL,
    is_profile_completed boolean DEFAULT false NOT NULL,
    full_name character varying(128),
    business_name character varying(256),
    city character varying(128),
    area character varying(258),
    address text,
    kitchen_type character varying(128),
    profile_image text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    provider_id uuid NOT NULL,
    hashed_password character varying(255) NOT NULL,
    pincode integer,
    landmark character varying(128),
    state character varying(64),
    house_no character varying(64)
);


ALTER TABLE provider.providers OWNER TO postgres;

--
-- Name: providers_id_seq; Type: SEQUENCE; Schema: provider; Owner: postgres
--

ALTER TABLE provider.providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME provider.providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: otp_logs; Type: TABLE DATA; Schema: provider; Owner: postgres
--

COPY provider.otp_logs (otp_log_id, mobile_number, otp, expires_at, is_verified, attempts, created_at, hashed_password) FROM stdin;
23a8ea45-a553-4c6e-93bd-55123583ff85	7999411794	825573	2026-05-19 08:23:25.137911+05:30	f	0	2026-05-19 08:18:46.42339+05:30	\N
24db31ae-82fe-4dca-bffb-2fe54a3c5876	7999411794	432273	2026-05-19 14:08:44.897203+05:30	f	0	2026-05-19 08:24:06.12962+05:30	\N
fa859cb4-03b5-4720-b106-951992e74651	7999411794	473390	2026-05-19 14:30:30.124778+05:30	f	0	2026-05-19 08:45:30.126695+05:30	\N
bc399d61-4ea6-4020-a640-602d3ee39906	7999411794	967003	2026-05-19 14:30:31.844557+05:30	f	0	2026-05-19 08:45:31.844557+05:30	\N
993fc15c-0a1f-452b-8fef-48508ec2d9c9	7999411794	860264	2026-05-19 14:30:34.719491+05:30	t	2	2026-05-19 08:45:34.720608+05:30	\N
d8d41b96-9885-477d-aedc-6d1d685bb7a7	7999411794	252095	2026-05-19 15:01:11.072799+05:30	t	0	2026-05-19 09:16:32.347878+05:30	\N
45ddcbf6-e67f-445d-88be-d2860820581d	7999411794	836877	2026-05-19 16:52:08.696949+05:30	t	0	2026-05-19 11:07:29.998808+05:30	$2b$12$Q6MuE0GGLNTMsRMpgAmhDuLKXOtyGJDaPY8jEB5/9eqZf5.uEkyNK
ce144036-dfb3-45c5-9b10-81bb20752d0e	7999411794	849741	2026-05-19 16:54:30.049387+05:30	t	0	2026-05-19 11:09:30.049387+05:30	$2b$12$EGwpugJQL4UGMp9S..Fecu1FOs02hwsV6Ln/IztbrCpfDuBSR9Rhy
5fa914ab-8f65-4e71-ae18-7637760e14e0	7999411794	231088	2026-05-19 16:57:22.122185+05:30	t	0	2026-05-19 11:12:22.122185+05:30	$2b$12$VgjJf7ggbzX9n8ml1dcaHO9RYbHGYZtBiDqTLeX.q2i6Nya.qleTS
e2eec8c6-5613-4de3-a569-89fa41764ccc	6264677824	182620	2026-05-21 12:13:32.184725+05:30	t	0	2026-05-21 06:28:53.469746+05:30	$2b$12$nYHiB/pjPbtU02zxlhc4LOVuchO.eAiVephk9SfG61IbIutJzW78S
6dbd0b43-506c-4df1-a99c-29805c93a5be	6264677824	662431	2026-05-21 12:14:51.836093+05:30	t	0	2026-05-21 06:29:51.837074+05:30	$2b$12$LhsO1mFl6yWa2IbB6wyb3.DJ6B4qB2hGRYMqFmAIXafvdbnDnUu62
36105b4a-5b51-4bac-8cb7-07f985c7f26d	6264677824	283562	2026-05-21 12:16:38.349438+05:30	t	0	2026-05-21 06:31:38.35044+05:30	$2b$12$6KmiTddz923RANsepYqfOuoUIwl.ul9qygEWIVMeEUwPiYdl.OB2q
\.


--
-- Data for Name: providers; Type: TABLE DATA; Schema: provider; Owner: postgres
--

COPY provider.providers (id, mobile_number, is_mobile_verified, is_profile_completed, full_name, business_name, city, area, address, kitchen_type, profile_image, created_at, updated_at, provider_id, hashed_password, pincode, landmark, state, house_no) FROM stdin;
2	6264677824	t	f	\N	\N	\N	\N	\N	\N	\N	2026-05-21 11:59:37.769159+05:30	2026-05-21 12:01:54.95173+05:30	78ccb795-8af5-4735-b128-3b389939a813	$2b$12$6KmiTddz923RANsepYqfOuoUIwl.ul9qygEWIVMeEUwPiYdl.OB2q	\N	\N	\N	\N
1	7999411794	t	t	Inder Rajput	Bhojnalaya	Delhi	Mandaveli	D303 west vinod nager mandaaveli	veg	\N	2026-05-19 16:42:33.571203+05:30	2026-05-21 17:02:10.975556+05:30	b28d33e2-831b-44b1-a8b9-e93aa570fcaa	$2b$12$VgjJf7ggbzX9n8ml1dcaHO9RYbHGYZtBiDqTLeX.q2i6Nya.qleTS	110092	Shri Ram Chock	Delhi	D303
\.


--
-- Name: providers_id_seq; Type: SEQUENCE SET; Schema: provider; Owner: postgres
--

SELECT pg_catalog.setval('provider.providers_id_seq', 2, true);


--
-- Name: otp_logs otp_logs_pkey; Type: CONSTRAINT; Schema: provider; Owner: postgres
--

ALTER TABLE ONLY provider.otp_logs
    ADD CONSTRAINT otp_logs_pkey PRIMARY KEY (otp_log_id);


--
-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: provider; Owner: postgres
--

ALTER TABLE ONLY provider.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

