"""add notifications and user sessions

Revision ID: 1a3eae9e0b28
Revises: 00008c8b8e30
Create Date: 2026-06-08 17:28:23.249445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3eae9e0b28'
down_revision: Union[str, Sequence[str], None] = '00008c8b8e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['user_id'], source_schema='auth', referent_schema='auth')
    op.create_unique_constraint('user_sessions_refresh_token_key', 'user_sessions', ['refresh_token'], schema='auth')
    op.create_foreign_key('fk_sessions_user', 'user_sessions', 'users', ['user_id'], ['user_id'], source_schema='auth', referent_schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sessions_user', 'user_sessions', schema='auth', type_='foreignkey')
    op.drop_constraint('user_sessions_refresh_token_key', 'user_sessions', schema='auth', type_='unique')
    op.drop_constraint('notifications_user_id_fkey', 'notifications', schema='auth', type_='foreignkey')
    # ### end Alembic commands ###
