"""initial migration

Revision ID: 825c9b7728f6
Revises: 
Create Date: 2026-06-08 16:48:39.878333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '825c9b7728f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('otp_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_otp_logs_contact'), 'otp_logs', ['contact'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_otp_logs_id'), 'otp_logs', ['id'], unique=False, schema='auth')
    op.create_table('user_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.Text(), nullable=False),
    sa.Column('address_line2', sa.Text(), nullable=True),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pin_code', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=6), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_user_addresses_id'), 'user_addresses', ['id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False, schema='auth')
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_profile_completed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('referral_code', sa.String(length=12), nullable=True),
    sa.Column('referred_by', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_id'), 'users', ['id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_phone'), 'users', ['phone'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_user_id'), 'users', ['user_id'], unique=True, schema='auth')
    op.create_table('menu_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=150), nullable=False),
    sa.Column('category_slug', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id'),
    sa.UniqueConstraint('category_slug'),
    schema='master'
    )
    op.create_index(op.f('ix_master_menu_categories_id'), 'menu_categories', ['id'], unique=False, schema='master')
    op.create_table('service_unavailable_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('house_no', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('requested_from', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id'),
    schema='master'
    )
    op.create_table('serviceable_pincodes',
    sa.Column('pincode_id', sa.BigInteger(), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('pincode_id'),
    sa.UniqueConstraint('pincode'),
    schema='master'
    )
    op.create_index(op.f('ix_master_serviceable_pincodes_pincode_id'), 'serviceable_pincodes', ['pincode_id'], unique=False, schema='master')
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_type', sa.String(length=30), nullable=False),
    sa.Column('meal_slot', sa.String(length=20), nullable=False),
    sa.Column('duration_days', sa.SmallInteger(), nullable=False),
    sa.Column('free_skips', sa.SmallInteger(), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_subscription_plans_id'), 'subscription_plans', ['id'], unique=False, schema='master')
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('against', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_urls', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='provider'
    )
    op.create_index(op.f('ix_provider_complaints_id'), 'complaints', ['id'], unique=False, schema='provider')
    op.create_index(op.f('ix_provider_complaints_user_id'), 'complaints', ['user_id'], unique=False, schema='provider')
    op.create_table('otp_logs',
    sa.Column('otp_log_id', sa.UUID(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('otp_log_id'),
    schema='provider'
    )
    op.create_index(op.f('ix_provider_otp_logs_mobile_number'), 'otp_logs', ['mobile_number'], unique=False, schema='provider')
    op.create_index(op.f('ix_provider_otp_logs_otp_log_id'), 'otp_logs', ['otp_log_id'], unique=False, schema='provider')
    op.create_table('provider_selected_packages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('selection_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selection_id'),
    schema='provider'
    )
    op.create_table('providers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_mobile_verified', sa.Boolean(), nullable=True),
    sa.Column('is_profile_completed', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('business_name', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('area', sa.String(length=256), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('kitchen_type', sa.String(length=128), nullable=True),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('house_no', sa.String(length=64), nullable=True),
    sa.Column('landmark', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('meal_service_type', sa.Enum('Breakfast', 'Lunch', 'Dinner', 'Lunch and Dinner', 'Lunch and Breakfast', 'Breakfast and Dinner', 'Lunch and Dinner and Breakfast', 'Full Day', name='meal_service_type', schema='provider'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='provider'
    )
    op.create_index(op.f('ix_provider_providers_id'), 'providers', ['id'], unique=False, schema='provider')
    op.create_index(op.f('ix_provider_providers_mobile_number'), 'providers', ['mobile_number'], unique=True, schema='provider')
    op.create_index(op.f('ix_provider_providers_provider_id'), 'providers', ['provider_id'], unique=True, schema='provider')
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('vendor_rating', sa.SmallInteger(), nullable=False),
    sa.Column('package_rating', sa.SmallInteger(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='provider'
    )
    op.create_index(op.f('ix_provider_reviews_id'), 'reviews', ['id'], unique=False, schema='provider')
    op.create_index(op.f('ix_provider_reviews_user_id'), 'reviews', ['user_id'], unique=False, schema='provider')
    op.create_index(op.f('ix_provider_reviews_vendor_id'), 'reviews', ['vendor_id'], unique=False, schema='provider')
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('extra_order_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_order_id', sa.Text(), nullable=True),
    sa.Column('gateway_txn_id', sa.Text(), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='subscription'
    )
    op.create_index(op.f('ix_subscription_payments_id'), 'payments', ['id'], unique=False, schema='subscription')
    op.create_index(op.f('ix_subscription_payments_user_id'), 'payments', ['user_id'], unique=False, schema='subscription')
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('user_address_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meal_slot', sa.String(length=20), nullable=False),
    sa.Column('subscription_type', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('free_skips_total', sa.SmallInteger(), nullable=True),
    sa.Column('free_skips_used', sa.SmallInteger(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='subscription'
    )
    op.create_index(op.f('ix_subscription_subscriptions_id'), 'subscriptions', ['id'], unique=False, schema='subscription')
    op.create_index(op.f('ix_subscription_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False, schema='subscription')
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='subscription'
    )
    op.create_index(op.f('ix_subscription_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False, schema='subscription')
    op.create_index(op.f('ix_subscription_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False, schema='subscription')
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='subscription'
    )
    op.create_index(op.f('ix_subscription_wallets_id'), 'wallets', ['id'], unique=False, schema='subscription')
    op.create_index(op.f('ix_subscription_wallets_user_id'), 'wallets', ['user_id'], unique=True, schema='subscription')
    op.create_table('menu_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meal_type', sa.String(length=50), nullable=True),
    sa.Column('food_type', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discounted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_subscription_available', sa.Boolean(), nullable=True),
    sa.Column('subscription_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['master.menu_categories.category_id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.providers.provider_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_menu_packages_id'), 'menu_packages', ['id'], unique=False, schema='master')
    op.create_table('subscription_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='subscription'
    )
    op.create_index(op.f('ix_subscription_subscription_packages_id'), 'subscription_packages', ['id'], unique=False, schema='subscription')
    op.create_table('menu_package_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['master.menu_packages.package_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_menu_package_images_id'), 'menu_package_images', ['id'], unique=False, schema='master')
    op.create_table('menu_package_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('item_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['master.menu_packages.package_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_menu_package_items_id'), 'menu_package_items', ['id'], unique=False, schema='master')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_menu_package_items_id'), table_name='menu_package_items', schema='master')
    op.drop_table('menu_package_items', schema='master')
    op.drop_index(op.f('ix_master_menu_package_images_id'), table_name='menu_package_images', schema='master')
    op.drop_table('menu_package_images', schema='master')
    op.drop_index(op.f('ix_subscription_subscription_packages_id'), table_name='subscription_packages', schema='subscription')
    op.drop_table('subscription_packages', schema='subscription')
    op.drop_index(op.f('ix_master_menu_packages_id'), table_name='menu_packages', schema='master')
    op.drop_table('menu_packages', schema='master')
    op.drop_index(op.f('ix_subscription_wallets_user_id'), table_name='wallets', schema='subscription')
    op.drop_index(op.f('ix_subscription_wallets_id'), table_name='wallets', schema='subscription')
    op.drop_table('wallets', schema='subscription')
    op.drop_index(op.f('ix_subscription_wallet_transactions_user_id'), table_name='wallet_transactions', schema='subscription')
    op.drop_index(op.f('ix_subscription_wallet_transactions_id'), table_name='wallet_transactions', schema='subscription')
    op.drop_table('wallet_transactions', schema='subscription')
    op.drop_index(op.f('ix_subscription_subscriptions_user_id'), table_name='subscriptions', schema='subscription')
    op.drop_index(op.f('ix_subscription_subscriptions_id'), table_name='subscriptions', schema='subscription')
    op.drop_table('subscriptions', schema='subscription')
    op.drop_index(op.f('ix_subscription_payments_user_id'), table_name='payments', schema='subscription')
    op.drop_index(op.f('ix_subscription_payments_id'), table_name='payments', schema='subscription')
    op.drop_table('payments', schema='subscription')
    op.drop_index(op.f('ix_provider_reviews_vendor_id'), table_name='reviews', schema='provider')
    op.drop_index(op.f('ix_provider_reviews_user_id'), table_name='reviews', schema='provider')
    op.drop_index(op.f('ix_provider_reviews_id'), table_name='reviews', schema='provider')
    op.drop_table('reviews', schema='provider')
    op.drop_index(op.f('ix_provider_providers_provider_id'), table_name='providers', schema='provider')
    op.drop_index(op.f('ix_provider_providers_mobile_number'), table_name='providers', schema='provider')
    op.drop_index(op.f('ix_provider_providers_id'), table_name='providers', schema='provider')
    op.drop_table('providers', schema='provider')
    op.drop_table('provider_selected_packages', schema='provider')
    op.drop_index(op.f('ix_provider_otp_logs_otp_log_id'), table_name='otp_logs', schema='provider')
    op.drop_index(op.f('ix_provider_otp_logs_mobile_number'), table_name='otp_logs', schema='provider')
    op.drop_table('otp_logs', schema='provider')
    op.drop_index(op.f('ix_provider_complaints_user_id'), table_name='complaints', schema='provider')
    op.drop_index(op.f('ix_provider_complaints_id'), table_name='complaints', schema='provider')
    op.drop_table('complaints', schema='provider')
    op.drop_index(op.f('ix_master_subscription_plans_id'), table_name='subscription_plans', schema='master')
    op.drop_table('subscription_plans', schema='master')
    op.drop_index(op.f('ix_master_serviceable_pincodes_pincode_id'), table_name='serviceable_pincodes', schema='master')
    op.drop_table('serviceable_pincodes', schema='master')
    op.drop_table('service_unavailable_logs', schema='master')
    op.drop_index(op.f('ix_master_menu_categories_id'), table_name='menu_categories', schema='master')
    op.drop_table('menu_categories', schema='master')
    op.drop_index(op.f('ix_auth_users_user_id'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_phone'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_id'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_auth_user_addresses_user_id'), table_name='user_addresses', schema='auth')
    op.drop_index(op.f('ix_auth_user_addresses_id'), table_name='user_addresses', schema='auth')
    op.drop_table('user_addresses', schema='auth')
    op.drop_index(op.f('ix_auth_otp_logs_id'), table_name='otp_logs', schema='auth')
    op.drop_index(op.f('ix_auth_otp_logs_contact'), table_name='otp_logs', schema='auth')
    op.drop_table('otp_logs', schema='auth')
    # ### end Alembic commands ###
